### ISSUE TITLE
`socklog-overlay` doesn't work with the latest `s6-overlay`

### ISSUE THREAD

**Issue by fadeevab** [just-containers/socklog-overlay#9]
`s6-overlay` version: 3.1.4.2
`socklog-overlay` version: 3.1.2-0

`socklog` fails to start at `docker run`.

**Problems:**
1. `s6-overlay` doesn't have binaries in the `/usr/bin` path anymore, all binaries are moved to `/command` folder.
    1.  `#!/usr/bin/execlineb -P` doesn't work.
    2. **Quickfix**: Unpack `s6-overlay-symlinks-arch.tar.xz` additionally.
2.  `cont-init.d/~-socklog` fails to run due to numerous errors:
    1. `s6-test` cannot be found (it was replaced with `eltest`)
    2. `fix-attrs` cannot be found in paths (it's been wind down).
    3. `execlineb` and `printcontenv` cannot be found (unpack `s6-overlay-symlinks-arch.tar.xz` to fix).
    4. Even after fixing 3 items above the `/var/log/*` folders are not `chmod`ed in the end of the script due to some error (chmoding from Dockerfile works though).

**Comment by skarnet** [comment]
Going to make a pass on it and test things. Thanks for the report.

**Comment by skarnet** [comment]
Oh, wait. This is the github for socklog-overlay, not s6-overlay...

Yeah, that's expected. socklog-overlay won't work with s6-overlay v3. Instead, s6-overlay v3 provides a `syslogd-overlay-noarch.tar.xz` tarball that you can unpack and that will provide a syslogd service just like socklog did. The functionality has been integrated now!

**Comment by fadeevab** [comment]
For the record, it also works **without** `syslogd-overlay-noarch.tar.xz` but **with your own** rules in the directory `/etc/socklog.rules/*`.
In the Dockerfile:
1. Unpack  `s6-overlay-symlinks-arch.tar.xz`.
2. `rm /etc/socklog.rules/~`
3. `cp your-rules /etc/socklog.rules/`
4. `chown -R nobody:nogroup /var/log/yourlogs`

`your-rules`:
```
-
+^local.\.*
/var/log/yourlogs
```
